# Generated by Django 5.2.7 on 2025-11-21 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time_out',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
